services:
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    container_name: moeda-estudantil-db
    env_file: ./.env
    ports:
      - $POSTGRES_LOCAL_PORT:$POSTGRES_DOCKER_PORT
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DATABASE
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      dockerfile: Dockerfile
    depends_on:
      - postgres
    working_dir: /app
    container_name: moeda-estudantil-api
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/$POSTGRES_DATABASE?useSSL=false&createDatabaseIfNotExist=true

      - SPRING_DATASOURCE_USERNAME=$POSTGRES_USER
      - SPRING_DATASOURCE_PASSWORD=$POSTGRES_PASSWORD
      - MAIL_USERNAME=$MAIL_USERNAME
      - MAIL_PASSWORD=$MAIL_PASSWORD
    stdin_open: true
    tty: true

volumes:
  postgres_data:
